---
- hosts: all
  become: yes
  roles:
    - { role: archcore, tags: ['core', 'cli', 'gui'] }
    - { role: dotfiles, tags: ['dotfiles', 'cli', 'gui'] }
    - { role: x, tags: ['x', 'gui'] }
    - { role: tools, tags: ['tools', 'gui'] }
    - { role: pim, tags: ['pim', 'cli', 'gui'] }
    - { role: mail, tags: ['mail', 'cli', 'gui'] }
    - { role: audio, tags: ['audio', 'cli', 'gui'] }
    - { role: backup, tags: ['backup', 'cli', 'gui'] }
    - { role: ops, tags: ['ops', 'cli', 'gui'] }
    - { role: virt, tags: ['virt', 'cli', 'gui'] }
    - { role: dev, tags: ['dev', 'python', 'cli', 'gui'] }
    - { role: comm, tags: ['comm', 'cli', 'gui'] }
    - { role: media, tags: ['media', 'cli', 'gui'] }

- hosts: workstation
  become: yes
  roles:

- hosts: servers
  become: yes
  roles:

